### ISSUE TITLE
provider ^6.0.0 and chewie ^1.2.2, version solving failed

### ISSUE THREAD

**Issue by Arialena** [fluttercommunity/chewie#587]
Because chewie 1.2.2 depends on provider ^5.0.0 and no versions of chewie match >1.2.2 <2.0.0, chewie ^1.2.2 requires provider ^5.0.0.
So, becausedepends on both provider ^6.0.0 and chewie ^1.2.2, version solving failed.
pub get failed (1; So, because jytc_baby depends on both provider ^6.0.0 and chewie ^1.2.2, version solving failed.)

**Comment by javaherisaber** [comment]
Same issue when upgrading to Flutter 2.8.1

```
Because flutter_math_fork >=0.4.0 depends on provider ^6.0.0 and chewie 1.2.2 depends on provider ^5.0.0, flutter_math_fork >=0.4.0 is incompatible with chewie 1.2.2.
And because no versions of chewie match >1.2.2 <2.0.0, flutter_math_fork >=0.4.0 is incompatible with chewie ^1.2.2.
So, because zireh depends on both chewie ^1.2.2 and flutter_math_fork ^0.5.0, version solving failed.
pub get failed (1; So, because zireh depends on both chewie ^1.2.2 and flutter_math_fork ^0.5.0, version solving failed.)
```

**Comment by bhayatus** [comment]
```
dependency_overrides:
  provider: 6.0.1
```
  
 This should do the trick as a stopgap measure.

**Comment by Dansp** [comment]
> Same issue when upgrading to Flutter 2.8.1
> 
> ```
> Because flutter_math_fork >=0.4.0 depends on provider ^6.0.0 and chewie 1.2.2 depends on provider ^5.0.0, flutter_math_fork >=0.4.0 is incompatible with chewie 1.2.2.
> And because no versions of chewie match >1.2.2 <2.0.0, flutter_math_fork >=0.4.0 is incompatible with chewie ^1.2.2.
> So, because zireh depends on both chewie ^1.2.2 and flutter_math_fork ^0.5.0, version solving failed.
> pub get failed (1; So, because zireh depends on both chewie ^1.2.2 and flutter_math_fork ^0.5.0, version solving failed.)
> ```

Same error here

**Comment by WatchDogsDev** [comment]
Same here, Please upgrade the provider package

**Comment by rakeshparveen5** [comment]
Facing the same issue

**Comment by zbarbuto** [comment]
FTR this was already fixed in #548 (see changelog for 1.2.3) - still just waiting for version 1.2.3 to actually get published to pub.dev

**Comment by Hardas-Dharani** [comment]
just add this version 
and user provider: ^6.0.1
chewie:

**Comment by jagmit** [comment]
@Ahmadre  @brianegan Can we please get a version 1.2.3 release? The changes made in https://github.com/brianegan/chewie/pull/548 are critical for using `chewie` in real projects.

**Comment by diegotori** [comment]
Version `1.3.0` is now live on pub.dev, which upgrades `Provider` to `^6.0.1` as well as `wakelock` to the latest version.
