### ISSUE TITLE
1.2.3 publishing to pub.dev

### ISSUE THREAD

**Issue by bs-vasyl-trs** [fluttercommunity/chewie#592]
Hello.
First of all wanted to say thank you for your work and contribution into Flutter open source projects - you rock.
Could you please publish 1.2.3 verison to pub.dev as 1.2.2 blocks us from upgrating project packages.
Many thanks

**Comment by diegotori** [comment]
@Ahmadre gentle reminder regarding this. Thanks in advance.

**Comment by ekuleshov** [comment]
Before publishing to pub.dev, please update the wakelock (and any other dependencies) to the latest

**Comment by 31Carlton7** [comment]
When is this being published? My app build broke today.

**Comment by diegotori** [comment]
@brianegan I think we definitely need a new release. Even pointing the library to master doesn't look like it's gonna cut it.

@Ahmadre any plans for a new release for this issue, since lots of folks are waiting patiently for one? Thanks in advance.

**Comment by Nei1eveN** [comment]
Amy update on this?

**Comment by bbischler** [comment]
I need an update as well

**Comment by diegotori** [comment]
@Ahmadre just gently reminding you regarding this. Thanks in advance.

**Comment by WatchDogsDev** [comment]
Is this project maintained anymore ? A lot of dependency conflicts are here

**Comment by diegotori** [comment]
@WatchDogsDev I hear your frustration. As of today, I am now responsible for publishing new versions on pub.dev. Also, the project has been transferred to Flutter Community, which ensures it's long term commitment to this project.

One more thing, I'll publish a new build tonight.

**Comment by diegotori** [comment]
Version `1.3.0` has been published to [pub.dev](https://pub.dev/packages/chewie). Looks like updates are back on the menu, folks, courtesy of yours truly. Thank you for your patience.
