### ISSUE TITLE
Allow durations for the controls hide timer

### ISSUE THREAD

**Issue by doppio** [fluttercommunity/chewie#595]
Chewie waits 3 seconds after user interactions before hiding the controls. For my use case with a short video, 3 seconds feels way too long. I plan to fork Chewie to implement a new parameter for the duration. Would you accept a pull request for this feature?

**Comment by diegotori** [comment]
Yes, we definitely take PRs for this. Feel free to submit when you're ready and myself or [maherjaafar](https://github.com/maherjaafar) will review your proposed changes.
