### ISSUE TITLE
[feature-request] For android forward and backward controls like iOS

### ISSUE THREAD

**Issue by NikhilKukreja26** [fluttercommunity/chewie#615]
Hello,
I am using the chewie package for android and ios for video playing. In iOS, we have forward and backward controls so anyone can forward 15 sec or backward the 15 sec but on android, it is not possible can we have a double tap on right to forward it and on the left side 15 backward.

Thank you

**Comment by diegotori** [comment]
@NikhilKukreja26 if you have the capacity, I always accept Pull Requests and I'll be happy to review them. In terms of the changes, they should be made where the `CenterPlayButton` is rendered, within `MaterialControls._buildHitArea()`.

**Comment by NikhilKukreja26** [comment]
Thank you so much @diegotori for your reply I will definitely try it if I succeed I will definitely submit my pull request.

**Comment by GyanendroKh** [comment]
@diegotori As this issue hasn't had any activity in a while, I took the time to implement the feature just like you said and submitted a PR https://github.com/fluttercommunity/chewie/pull/703

Can you please check and merge if everything is good?
Thanks.
