### ISSUE TITLE
Customize Progress bar

### ISSUE THREAD

**Issue by arindammitra06** [fluttercommunity/chewie#620]
Hi There..
Thanks for the wonderful library. I was wondering if there is a way to change the progress_bar height. I see only colors can be changed using below example.
```
materialProgressColors: ChewieProgressColors(
          playedColor: Colors.white
),
      
```

Any suggestion would be helpful. I want to customize the progress bar. Thanks.

**Comment by diegotori** [comment]
@arindammitra06 `ChewieController` allows you to specify custom controls via the `customControls` property. This enables you to create controls to your liking.

For example, you can copy-paste either the Material or Cupertino controls and progress bar source code and customize it to your heart's content up to and including customizing the Progress Bar.

I hope this points you in the desired direction.

**Comment by arindammitra06** [comment]
Fantastic. Got it done. Thanks
