### ISSUE TITLE
How can I save the last watch time of the video?

### ISSUE THREAD

**Issue by burhanaksendir** [fluttercommunity/chewie#660]
I have created the video player using chewie controller.  I have a video list screen.  Touching any item opens the video player page.

I need to get the time where the user stopped the video watching either he had quit the app or came back or paused. How can I achieve this?

**Comment by Omi231** [comment]
you can get user's current timer where user has stopped/left playing by `chewieController?.videoPlayerController.value.position;`. Before disposing the video controllers save this duration value somewhere locally and when user plays same video again use `startAt:` inside `chewieControlleer` initializer.

**Comment by burhanaksendir** [comment]
Thank you.  If the application crashes or is closed by the system while the user is watching the video, the last value.  How can I save  position value?

**Comment by Omi231** [comment]
In 99.99% of the cases it wont crash unless you do some serious mistake but if you are still scared then you can run a timer inside initState and change/store the current progress value. If something wrong happens you will have last stored progress value which you an use next time video is played again.

**Comment by burhanaksendir** [comment]
Thank you very much for your help.
