### ISSUE TITLE
Can m3u8 use callback to handle encryption part

### ISSUE THREAD

**Issue by d1y** [fluttercommunity/chewie#661]
I got an m3u8 address, but it inserted a useless placeholder in its header (actually for encryption). Obviously, I need to delete the previous paragraph. But how can I transfer the standard content to Chewie?

After you get the content, you will find that each paragraph of the content is a 'PNG'. In those years, Chewie could not parse it either. In fact, it has been disguised as a picture (PNG). It seems that you can get it correctly only by removing the magic value (89, 50, 43, 47) of the head TS ` video format is changed. It seems that Chewie does not provide callback to solve this problem. Ha, can the author answer this question? Thank you 👍🏻 

m3u8 file: http://sod.bunediy.com/20220802/19bluHUM/index.m3u8
one ts file: http://ali.static.yximgs.com/bs2/adcarsku/sku0a402b80-5531-4b7d-b428-bc0ec0219f03.png

![DeepinScreenshot_desktop_window_20220808232746](https://user-images.githubusercontent.com/45585937/183454873-323c9280-2550-4e98-aec8-912d3ee6fe31.png)

![DeepinScreenshot_desktop_window_20220808232810](https://user-images.githubusercontent.com/45585937/183454979-0f2ce4ca-5154-4721-b013-7c1af2a08f0e.png)

**Comment by maherjaafar** [comment]
Thank you @d1y for opening an issue. The chewie plugin is built on top of video_player so I think that this issue should be related to [video_player](https://pub.dev/packages/video_player).

**Comment by maherjaafar** [comment]
Thank you @d1y for opening an issue. The chewie plugin is built on top of video_player so I think that this issue should be related to [video_player](https://pub.dev/packages/video_player).
