### ISSUE TITLE
Play button is oversized after flutter 3.3.0

### ISSUE THREAD

**Issue by OutdatedGuy** [fluttercommunity/chewie#670]
After updating flutter to version `3.3.0`, the play/pause button (i.e. control button) on the video player is extremely oversized.
The replay button is not affected but only the play button. See the video.

Platform: Web
Chewie: ^1.3.4

[Video](https://user-images.githubusercontent.com/74326345/189362926-49085481-689c-4b93-ad6a-ebf8275db14d.mp4)

**Comment by diegotori** [comment]
@OutdatedGuy  addressed in version `1.3.5`, which was published just a short while ago. Please try that out.

**Comment by OutdatedGuy** [comment]
Yup it's resolved. Thank you.
