### ISSUE TITLE
can't use file_picker with chewie together

### ISSUE THREAD

**Issue by kamyar75** [fluttercommunity/chewie#737]
hi I upgraded my file_picker widget to 5.3.2 version and this version is using from win32 with version of 5.0.0 but the last version of chewie ( 1.5.0) is using from wakelock: ^0.6.2 , the wakelock widget use win32 with the version of 3.0.0 ,so I cant use together

**Comment by komangnopha** [comment]
use dependency_overrides for current workaround

dependency_overrides:
  win32: ^5.0.0

**Comment by diegotori** [comment]
@kamyar75 we managed to release `1.6.0` today, which migrated `wakelock` to `wakelock_plus`. As a result, the latter is now fully maintained by Flutter Community, thus ensuring its preservation the immediate and long term future.
