### ISSUE TITLE
package errors when pub get

### ISSUE THREAD

**Issue by fisforfaheem** [fluttercommunity/chewie#744]
Resolving dependencies...
    Because no versions of chewie match >1.5.0 <2.0.0 and chewie 1.5.0 depends on wakelock ^0.6.2, chewie ^1.5.0 requires wakelock ^0.6.2.
(1) So, because no versions of wakelock match >0.6.2 <0.7.0 and wakelock 0.6.2 depends on wakelock_windows ^0.2.0, chewie ^1.5.0 requires wakelock_windows ^0.2.0.

    Because no versions of wakelock_windows match >0.2.0 <0.2.1 and wakelock_windows >=0.2.1 depends on win32 ^3.0.0, wakelock_windows >0.2.0 requires win32 ^3.0.0.
    And because wakelock_windows 0.2.0 depends on win32 ^2.0.0, wakelock_windows >=0.2.0 requires win32 ^2.0.0 or ^3.0.0.
    And because chewie ^1.5.0 requires wakelock_windows ^0.2.0 (1), chewie ^1.5.0 requires win32 ^2.0.0 or ^3.0.0.
    And because device_info_plus >=9.0.1 depends on win32 >=4.0.0 <6.0.0, chewie ^1.5.0 is incompatible with device_info_plus >=9.0.1.
    So, because ai_mockinterview depends on both device_info_plus ^9.0.2 and chewie ^1.5.0, version solving failed.
exit code 1

--

**Comment by hey-nicolasklein** [comment]
Second that, for using with the other *_plus packages such as package_info_plus and share_plus. Because of the chewie dependency I cannot upgrade those to their next major version.

**Comment by diegotori** [comment]
Library is now using `wakelock_plus` as per #747.

**Comment by fisforfaheem** [comment]
better solution?
