### ISSUE TITLE
package error when pub get

### ISSUE THREAD

**Issue by yangsfang** [fluttercommunity/chewie#752]
Flutter version: 3.7.12
Host Platform: Windows 11

Cloning the example project of `chewie` and running `flutter pub get` fails because the newly introduced `wakelock_plus` can only be built on Flutter 3.10. 

> Because every version of flutter from sdk depends on meta 1.8.0 and every version of wakelock_plus depends on meta ^1.9.1, flutter from sdk is incompatible with wakelock_plus.
> And because every version of chewie from path depends on wakelock_plus ^1.0.0+2, flutter from sdk is incompatible with chewie from path.
> So, because chewie_example depends on both chewie from path and flutter from sdk, version solving failed.

The documentation on pub.dev says `chewie` has a min dart SDK of 2.17 which is misleading, because the min SDK to successfully resolve the package is Dart 3.0.

![image](https://github.com/fluttercommunity/chewie/assets/31492969/646cf089-13a1-4711-a3a9-bd4edd451481)

We could do one of:

1. Keep the Dart 3.0 SDK requirement, and update the documentation to accurately reflect the min SDK requirement
2. Revert the dependency on `wakelock_plus` so `chewie` can be built with Dart 2.17-2.19 for the time being
3. Change `wakelock_plus` to work on Dart SDK 2.17-2.19

**Comment by diegotori** [comment]
@yangsfang since I also manage `wakelock_plus` I'm in the process of downgrading `meta` to work on versions below Flutter `3.10`.

See https://github.com/fluttercommunity/chewie/issues/752 for more info.

**Comment by diegotori** [comment]
@yangsfang Just published version [1.7.0](https://pub.dev/packages/chewie/versions/1.7.0), which now supports at least Dart `2.18` and Flutter `3.3.0` respectively.

Please let me know if this suffices. Thanks.

**Comment by yangsfang** [comment]
This is fine. Thank you.
