### ISSUE TITLE
Failed to initialize -> exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException

### ISSUE THREAD

**Issue by kaganzdmr58** [fluttercommunity/chewie#761]
Hi all, 
I have a problem for initialized VideoController 

Video codec error
E/MediaCodecVideoRenderer(15386):   com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, Format(0, null, null, video/avc, avc1.640028, -1, null, [1280, 720, -1.0], [-1, -1])

Playback error
E/ExoPlayerImplInternal(15386):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(0, null, null, video/avc, avc1.640028, -1, null, [1280, 720, -1.0], [-1, -1]), format_supported=YES

ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(0, null, null, video/avc, avc1.640028, -1, null, [1280, 720, -1.0], [-1, -1]), format_supported=YES, null, null)

https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/video/MediaCodecVideoRenderer.html
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ExoPlaybackException.html

and When I followed the errors, I learned that exoplayer 2 should be migrated androidx.media3. Can you give feedback on whether the update will be made or you can offer another solution without it?

**Comment by mhbdev** [comment]
Same here!

**Comment by diegotori** [comment]
@kaganzdmr58 this library is merely a UI wrapper around `video_player`. 

Since the issue lies there, that means you will have to bring it up with the Flutter team, since this is beyond the scope of what I'm able to address.
