### ISSUE TITLE
Progress bar does not follow drag

### ISSUE THREAD

**Issue by koutaro-masaki** [fluttercommunity/chewie#789]
When you grab and slide the progress bar, you would expect the pointer to follow your finger, but Chewie doesn't do that.
It seems that the `_latestDraggableOffset` is not passed to the `StaticProgressBar` and the update is not reflected, is this intended?

https://github.com/fluttercommunity/chewie/pull/712

**Comment by basemkhirat** [comment]
good to fix this

**Comment by ashanftw** [comment]
https://github.com/fluttercommunity/chewie/issues/797

im having the same issue

**Comment by diegotori** [comment]
@koutaro-masaki I'll look into this sometime this week. If you have a PR that fixes this, I'll be happy to review it. Thanks.

**Comment by ashanftw** [comment]
@diegotori Would you be able to publish the fix to the package?

**Comment by diegotori** [comment]
I'll make an effort first thing tomorrow. Gonna be out of the country for two weeks, so I'll try to squeeze it before I head out.

**Comment by diegotori** [comment]
Published in version `1.7.2`.

**Comment by ashanftw** [comment]
Thank you!
