### ISSUE TITLE
i need to change Chewie video player for flutter take up the whole screen size regardless of video dimensions?

### ISSUE THREAD

**Issue by abdelrahman-abied** [fluttercommunity/chewie#809]

**Comment by HeySitam** [comment]
Yep, that's an issue with Chewie. I have faced the same while developing a short video player app.

**Comment by wizi-sky** [comment]
Hi, bro, have you found a suitable solution?

**Comment by HeySitam** [comment]
I have found one solution. Will let you know soon.

**Comment by abdelrahman-abied** [comment]
> Hi, bro, have you found a suitable solution?

import 'package:chewie/chewie.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

class VideoScreen extends StatefulWidget {
  const VideoScreen({super.key});

  @override
  State<VideoScreen> createState() => _VideoScreenState();
}

class _VideoScreenState extends State<VideoScreen> {
  final videoPlayerController = VideoPlayerController.networkUrl(
    Uri.parse('Url'),
  );
  late final ChewieController chewieController;
  @override
  void initState() {
    chewieController = ChewieController(
      videoPlayerController: videoPlayerController,
      aspectRatio: .56,
      autoPlay: true,
      looping: true,
      fullScreenByDefault: false,
      placeholder: const Center(
        child: CircularProgressIndicator(),
      ),
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          children: [
            Expanded(
              child: Chewie(
                controller: chewieController,
              ),
            ),
          ],
        ),
      ),
    );
  }

  @override
  dispose() {
    videoPlayerController.dispose();
    chewieController.dispose();
    super.dispose();
  }
}

**Comment by niceumang-tech** [comment]
@abdelrahman-abied For me if landscape view then aspect ratio is 2.5
