### ISSUE TITLE
Dependency upgrade to allow 'web 1.0.0'

### ISSUE THREAD

**Issue by gabrielginter** [fluttercommunity/chewie#848]
Upgrade wakelock_plus dependency to allow the use of web 1.0.0

**Comment by zs-dima** [comment]
+1

**Comment by diegotori** [comment]
@gabrielginter in the meantime, if you run `flutter upgrade`, it will pull in `wakelock_plus` version `1.2.8`, which supports web `1.0.0`.

If you do that, then there's no need to upgrade the dependency immediately, since`wakelock_plus` is transitive, thus `flutter upgrade` will do the trick.

**Comment by gabrielginter** [comment]
@diegotori  I can see wakelock_plus updated recently, after upgrading web to 1.0.0, it worked, thanks
