### ISSUE TITLE
landscape on iOS in full screen

### ISSUE THREAD

**Issue by Mil0R** [fluttercommunity/chewie#86]
It is still portrait after entering full screen, how to make it to landscape?
or add a listener on the event for enter/exit full screen?

**Comment by cbenhagen** [comment]
This is currently hardcoded behaviour to only rotate on android: https://github.com/brianegan/chewie/blob/b135a466622daf080282b756cf6749844ed05632/lib/src/chewie_player.dart#L196-L200

The stock video player on iOS and Youtube for iOS behave the same. But for me it also does not feel very user friendly. We could make this an option? @brianegan what do you think?

**Comment by brianegan** [comment]
Maybe this can be another config option? 

I did it this way to mimic the default behavior I was seeing on Stock Android with Videos, but I imagine other providers like Samsung may do things differently.

**Comment by localpcguy** [comment]
Is this something that can be worked around in implementation code, or does it need to be in the Chewie plugin? We've run into this recently and I found this issue looking to see how to fix this.

It's definitely an issue, as most phones (iOS and Android) that I've used rotate the video to be landscape when going to full screen. This does not seem like it should be hardcoded for Android, but rather should default to horizontal videos when a user chooses to go full screen.

**Comment by sfaujour** [comment]
The problem here is that currently in iOS you can't perform a device rotation without physical rotate the device by default.

After so many people had this problem, i published a basic package for that.
https://pub.dartlang.org/packages/auto_orientation

Maybe it's what you need, but i think you have override the `_buildFullScreenVideo` Method of Chewie with a Custom Scaffold like i did, described in the package.

**Comment by localpcguy** [comment]
@sfaujour is it possible to publish the source code for AutoOrientation to a Github repo and update the pub package to reference that Github repo? We'd like to potentially use it, but we prefer to review code we pull in prior to using it.

**Comment by sfaujour** [comment]
Sure i'll do that. Today for sure!

**Comment by sfaujour** [comment]
@localpcguy I've linked the package. It's really a simple package, because i just implement the basic things for simple rotating.

**Comment by sfaujour** [comment]
I've also did a PR for the possibility to override the page builder functionality.
There is also an example how you could override the fullscreen page builder  with a custom `VideoScaffold`

**Comment by sfaujour** [comment]
@Mil0R @brianegan I think this can be closed, or?

**Comment by localpcguy** [comment]
Sorry it's taken me so long, but I will be implementing this fix in our app early next week. Looks good to me but will report back if I run into any issues.

**Comment by localpcguy** [comment]
I implemented the solution and auto-rotation plugin described above, and it looks good so far.
